### PR TITLE
update items db to 18.08.30.00

### PR DESCRIPTION
**Pull request by Nadyita**
Wanted people to know by means of this that the item extractor does not work under Linux. Took me ages to install a Windows just for this -.-

### CODE REVIEW

**Comment by bigwheels16** [comment]
I'll take a look at this.  Did you manually add those entries to the aodb file?  That is going to be problematic since the tool by default adds them alphabetically.  If will cause conflicts when it's run for the next update.  Also, what trouble did you have getting the extract tool to run in Linux?  I've never tried to run it on linux since I don't have AO running on Linux, but if you have access to the resource db, then it should run on Linux just fine.

**Comment by Nadyita** [comment]
Yes, I added them manually. Shall I sort the file alphabetically and update the pull request?

The error from the extractor is:

```
$ java -cp ".:lib/*" com.jkbff.ao.itemsextractor.Program -d /home/mark/Games/AOClassic/drive_c/Funcom/Anarchy\ Online/
2018-10-18 23:34:49,287 DEBUG [main] (Runner.scala:30) - reading index file entries
2018-10-18 23:34:58,226 ERROR [main] (Program.scala:24) -
java.io.EOFException
        at java.io.RandomAccessFile.readFully(RandomAccessFile.java:438)
        at java.io.RandomAccessFile.readFully(RandomAccessFile.java:416)
        at com.jkbff.ao.itemsextractor.rdb.RDBFunctions$.readLittleEndianInt(RDBFunctions.scala:13)
        at com.jkbff.ao.itemsextractor.rdb.RDBExtractor.parseAttribute(RDBExtractor.scala:45)
        at com.jkbff.ao.itemsextractor.rdb.RDBExtractor$$anonfun$1.apply(RDBExtractor.scala:20)
        at com.jkbff.ao.itemsextractor.rdb.RDBExtractor$$anonfun$1.apply(RDBExtractor.scala:20)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:142)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:142)
        at scala.collection.immutable.NumericRange.foreach(NumericRange.scala:73)
        at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:142)
        at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
        at com.jkbff.ao.itemsextractor.rdb.RDBExtractor.readItem(RDBExtractor.scala:20)
        at com.jkbff.ao.itemsextractor.Runner$$anonfun$1.apply(Runner.scala:31)
        at com.jkbff.ao.itemsextractor.Runner$$anonfun$1.apply(Runner.scala:31)
        at scala.collection.immutable.List.map(List.scala:277)
        at com.jkbff.ao.itemsextractor.Runner.getEntries(Runner.scala:31)
        at com.jkbff.ao.itemsextractor.Runner.run(Runner.scala:26)
        at com.jkbff.ao.itemsextractor.Program$.delayedEndpoint$com$jkbff$ao$itemsextractor$Program$1(Program.scala:27)
        at com.jkbff.ao.itemsextractor.Program$delayedInit$body.apply(Program.scala:9)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at com.jkbff.ao.itemsextractor.Program$.main(Program.scala:9)
        at com.jkbff.ao.itemsextractor.Program.main(Program.scala)
```

**Comment by bigwheels16** [comment]
Hmm, I'm not sure why it is not working on windows.  I will take a look at that if I have time.

**Comment by bigwheels16** [comment]
Rather than sorting the results, it would be better to just use the exact files that the items extractor produces since it produces the files in the correct format/sort order.  Also, there should be a weapons file that goes in the SKILLS_MODULE, although it may not have had any changes.

**Comment by bigwheels16** [comment]
Rather than sorting the results, it would be better to just use the exact files that the items extractor produces since it produces the files in the correct format/sort order.  Also, there should be a weapons file that goes in the SKILLS_MODULE, although it may not have had any changes.

**Comment by bigwheels16** [comment]
do you want me to update the files with the right ordering?

**Comment by bigwheels16** [comment]
do you want me to update the files with the right ordering?

**Comment by bigwheels16** [comment]
do you want me to update the files with the right ordering?

**Comment by bigwheels16** [comment]
do you want me to update the files with the right ordering?

**Comment by bigwheels16** [comment]
closing this as it is now superseded by https://github.com/Budabot/Budabot/pull/15

**Pull request closed without merging**
