### PR TITLE
Updated URL links for items to use aoitems.com

### PR DESCRIPTION
**Pull request by zyamada**
AOItems is much more up to date than auno. Also removed non-needed whitespace characters from IRC module.

### CODE REVIEW

**Comment by zyamada** [comment]
Fixed

**Comment by bigwheels16** [comment]
ok that looks good.  can you fix the links in modules/GUIDE_MODULE/guides/atrox.txt and then i think it should be good to merge

**Comment by zyamada** [comment]
Sorry about that! Completely slipped my mind.

Done.

**Comment by bigwheels16** [comment]
awesome, thanks for the contribution!

**Pull request merged**
